#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "grist"
name = "Grist"
description.en = "Modern relational spreadsheet"
description.fr = "Feuille de calcul relationnelle moderne"

version = "1.1.9~ynh1"

maintainers = ["fflorent"]

[upstream]
license = "AGPL-3.0-only"
website = "https://getgrist.com"
demo = "https://docs.getgrist.com"
admindoc = "https://www.getgrist.com/product/self-managed/"
userdoc = "https://support.getgrist.com/"
code = "https://github.com/gristlabs/grist-core/"
fund = "https://github.com/sponsors/gristlabs"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = true

sso = true

disk = "1.5G"
ram.build = "1500M"
ram.runtime = "150M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["fr", "en"]
    default = "en"

    [install.admin]
    type = "user"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/gristlabs/grist-core/archive/refs/tags/v1.1.9.tar.gz"
        sha256 = "1b910a05beccf17d0bfd2d703b2346aa416adca2f791609c40a058f3b184e49f"

        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
    login.url = "/auth/login"
    login.show_tile = false
    login.allowed = "all_users"

    [resources.ports]
    main.default = 8484

    [resources.apt]
    packages = "python3.9, python3.9-venv"

    extras.yarn.repo = "deb https://dl.yarnpkg.com/debian/ stable main"
    extras.yarn.key = "https://dl.yarnpkg.com/debian/pubkey.gpg"
    extras.yarn.packages = ["yarn"]
