#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    exclude = ["install.subdir", "install.nourl"]

    test_upgrade_from.c98a6fb2.name = "Upgrade from 1.1.10"
